services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      VITE_BASE_URL_API: http://localhost:3333
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    command: bun run dev
    networks:
      - operix-network

volumes:
  node_modules:

networks:
  operix-network:
    driver: bridge
