export const API_CONFIG = {
    STATUS_SERVICE: '/status-servico',
    STATUS_PAYMENT: '/status-pagamento',
    TYPES_PRODUCT: '/tipos-produto',
    ROLES: '/cargos',
    SUPPLIERS: '/fornecedores',
    AGENDA: '/agenda',
    SERVICES: '/servicos',
    ORDERS_OF_SERVICE: '/ordens-servico',
    USERS: '/usuarios',
    TENANTS: '/locatarios',
    PROFILE_ME: '/perfil/eu',
    PROFILE_COMPANY: '/perfil/empresa',
    PROFILE_SYSTEM: '/perfil/sistema',
    NOTIFICATIONS: '/notificacoes',
    STOCK: '/estoque',
    SALES: '/vendas',
    CLIENTS: '/clientes',
    SERVICE_PARTS: (serviceId) => `/servicos/${serviceId}/pecas`,
    EXTERNAL_SERVICE: (cod) => `/servicos/painel-externo/${cod}`,
    EXTERNAL_SERVICES: '/servicos/painel-externo',
    TIME_CLOCK: { CURRENT: '/ponto/me', HISTORY: '/ponto/me/historico', START: '/ponto/iniciar', STOP: '/ponto/encerrar', REQUEST: (id) => `/ponto/${id}/solicitar-ajuste`, ENTRIES: '/ponto/gerenciar', ADJUSTMENTS: '/ponto/ajustes', REVIEW: (id) => `/ponto/ajustes/${id}` },
    EXTERNAL_ACCESS_EXCHANGE: '/autenticacao/acesso-externo/trocar',
    EXTERNAL_ACCESS_PROFILE: '/perfil/acesso-externo',
    EXTERNAL_ACCESS_ROTATE: '/perfil/acesso-externo/rotacionar',
    AUTH: {
        LOGIN: '/autenticacao/login',
        INTERNAL_LOGIN: '/autenticacao/login-interno',
        REGISTER: '/autenticacao/registrar',
        CHECK_EMAIL: '/autenticacao/verificar-email-existencia',
        FORGOT_PASSWORD: '/autenticacao/recuperar-senha',
        RESET_PASSWORD: '/autenticacao/redefinir-senha',
        ONBOARDING: '/autenticacao/onboarding',
        REFRESH: '/autenticacao/renovar',
        LOGOUT: '/autenticacao/sair',
        ME: '/autenticacao/eu',
        AUTHORIZE: '/autenticacao/autorizar',
        CALLBACK: '/autenticacao/retorno'
    },
};
