export const API_CONFIG = {
    STATUS_SERVICE: '/status-servico',
    STATUS_PAYMENT: '/status-pagamento',
    TYPES_PRODUCT: '/tipos-produto',
    SERVICES: '/servicos',
    ORDERS_OF_SERVICE: '/ordens-servico',
    USERS: '/usuarios',
    TENANTS: '/locatarios',
    PROFILE_ME: '/perfil/eu',
    PROFILE_COMPANY: '/perfil/empresa',
    PROFILE_SYSTEM: '/perfil/sistema',
    NOTIFICATIONS: '/notificacoes',
    STOCK: '/estoque',
    SALES: '/vendas',
    CLIENTS: '/clientes',
    SERVICE_PARTS: (serviceId) => `/servicos/${serviceId}/pecas`,
    AUTH: {
        LOGIN: '/autenticacao/login',
        INTERNAL_LOGIN: '/autenticacao/login-interno',
        REGISTER: '/autenticacao/registrar',
        CHECK_EMAIL: '/autenticacao/verificar-email-existencia',
        FORGOT_PASSWORD: '/autenticacao/recuperar-senha',
        RESET_PASSWORD: '/autenticacao/redefinir-senha',
        ONBOARDING: '/autenticacao/onboarding',
        REFRESH: '/autenticacao/renovar',
        LOGOUT: '/autenticacao/sair',
        ME: '/autenticacao/eu',
        AUTHORIZE: '/autenticacao/autorizar',
        CALLBACK: '/autenticacao/retorno'
    },
};
