<script setup>
import { onMounted, ref } from 'vue';
import Axios from '@/services/axios';
import { API_CONFIG } from '@/services/api';
import { useToast } from 'primevue/usetoast';
const toast = useToast(); const entries = ref([]); const adjustments = ref([]); const loading = ref(false); const format = (v) => v ? new Date(v).toLocaleString('pt-BR') : '-'; const statusLabel = (status) => ({ open: 'Aberto', closed: 'Encerrado', pending: 'Pendente', approved: 'Aprovado', rejected: 'Rejeitado' }[status] || status || '-');
const load = async () => { loading.value = true; try { const [entryResponse, adjustmentResponse] = await Promise.all([Axios.get(API_CONFIG.TIME_CLOCK.ENTRIES), Axios.get(API_CONFIG.TIME_CLOCK.ADJUSTMENTS)]); entries.value = entryResponse.data || []; adjustments.value = adjustmentResponse.data || []; } catch (error) { toast.add({ severity: 'error', summary: 'Erro', detail: error.response?.data?.msg || 'Não foi possível carregar os lançamentos.', life: 5000 }); } finally { loading.value = false; } };
const review = async (row, status) => { try { await Axios.patch(API_CONFIG.TIME_CLOCK.REVIEW(row.id), { status }); await load(); toast.add({ severity: 'success', summary: 'Ponto', detail: status === 'approved' ? 'Ajuste aprovado.' : 'Ajuste rejeitado.', life: 4000 }); } catch (error) { toast.add({ severity: 'error', summary: 'Erro', detail: error.response?.data?.msg || 'Não foi possível revisar o ajuste.', life: 5000 }); } };
onMounted(load);
</script>
<template><Toast /><div class="grid"><div class="col-12"><div class="card"><div class="page-title-row"><h2 class="page-title">Ponto</h2><i class="pi pi-info-circle page-title-info" v-tooltip.top="'Consulte os lançamentos e analise solicitações de alteração do ponto.'" /></div><DataTable :value="entries" :loading="loading" paginator :rows="10" :rowsPerPageOptions="[10, 20, 50]" responsiveLayout="scroll"><template #empty>Nenhum lançamento encontrado.</template><Column field="user_name" header="Funcionário" /><Column field="started_at" header="Início"><template #body="{ data }">{{ format(data.started_at) }}</template></Column><Column field="ended_at" header="Fim"><template #body="{ data }">{{ format(data.ended_at) }}</template></Column><Column field="status" header="Situação"><template #body="{ data }">{{ statusLabel(data.status) }}</template></Column></DataTable></div></div><div class="col-12"><div class="card"><div class="page-title-row"><h3 class="page-title">Solicitações de alteração</h3><i class="pi pi-info-circle page-title-info" v-tooltip.top="'Analise e responda às solicitações de alteração do ponto.'" /></div><DataTable :value="adjustments" :loading="loading" responsiveLayout="scroll"><template #empty>Nenhuma solicitação pendente.</template><Column field="user_name" header="Funcionário" /><Column field="requested_started_at" header="Novo início"><template #body="{ data }">{{ format(data.requested_started_at) }}</template></Column><Column field="requested_ended_at" header="Novo fim"><template #body="{ data }">{{ format(data.requested_ended_at) }}</template></Column><Column field="reason" header="Motivo" /><Column header="Ações"><template #body="{ data }"><div v-if="data.status === 'pending'" class="flex gap-2"><Button icon="pi pi-check" severity="success" rounded aria-label="Aprovar" @click="review(data, 'approved')" /><Button icon="pi pi-times" severity="danger" rounded aria-label="Rejeitar" @click="review(data, 'rejected')" /></div><span v-else class="text-600">{{ statusLabel(data.status) }}</span></template></Column></DataTable></div></div></div></template>
