<script setup>
import { ref, watch } from 'vue';
import { useToast } from 'primevue/usetoast';
import Axios from '@/services/axios';
import { API_CONFIG } from '@/services/api';
import { hasPermission } from '@/services/authSession';
const props = defineProps({ modelValue: Boolean, serviceId: { type: Number, default: null }, saleId: { type: Number, default: null } });
const emit = defineEmits(['update:modelValue', 'saved']);
const toast = useToast(); const loading = ref(false); const services = ref([]); const sales = ref([]); const form = ref({ title: '', description: '', starts_at: '', service_id: null, sale_id: null, recurrence_rule: 'none', recurrence_until: '' });
const open = async () => { const now = new Date(); now.setMinutes(0, 0, 0); form.value = { title: '', description: '', starts_at: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}T${String(now.getHours()).padStart(2, '0')}:00`, service_id: props.serviceId, sale_id: props.saleId, recurrence_rule: 'none', recurrence_until: '' }; try { const requests = []; if (hasPermission('servicos.acesso')) requests.push(Axios.get(API_CONFIG.SERVICES)); if (hasPermission('vendas.acesso')) requests.push(Axios.get(API_CONFIG.SALES)); const responses = await Promise.all(requests); let index = 0; if (hasPermission('servicos.acesso')) services.value = responses[index++]?.data || []; if (hasPermission('vendas.acesso')) sales.value = responses[index]?.data || []; } catch { services.value = []; sales.value = []; } };
const save = async () => { if (!form.value.title.trim() || !form.value.starts_at) return toast.add({ severity: 'warn', summary: 'Validação', detail: 'Informe título e data.', life: 4000 }); if (form.value.recurrence_rule !== 'none' && !form.value.recurrence_until) return toast.add({ severity: 'warn', summary: 'Validação', detail: 'Informe até quando repetir.', life: 4000 }); loading.value = true; try { await Axios.post(API_CONFIG.AGENDA, { ...form.value, starts_at: new Date(form.value.starts_at).toISOString(), service_id: form.value.service_id || null, sale_id: form.value.sale_id || null, recurrence_until: form.value.recurrence_rule === 'none' ? null : form.value.recurrence_until }); toast.add({ severity: 'success', summary: 'Agenda', detail: 'Lembrete criado com sucesso.', life: 4000 }); emit('update:modelValue', false); emit('saved'); } catch (error) { toast.add({ severity: 'error', summary: 'Erro', detail: error.response?.data?.msg || 'Não foi possível criar o lembrete.', life: 5000 }); } finally { loading.value = false; } };
watch(() => props.modelValue, (value) => { if (value) open(); });
</script>
<template><Dialog :visible="modelValue" modal :style="{ width: 'clamp(22rem, 48vw, 42rem)' }" header="Adicionar lembrete" @update:visible="emit('update:modelValue', $event)"><div class="grid p-fluid mt-3"><div class="field col-12"><span class="p-float-label"><InputText id="quickReminderTitle" v-model="form.title" /><label for="quickReminderTitle"><span class="text-red-500">*</span> Título</label></span></div><div class="field col-12 md:col-6"><span class="p-float-label"><InputText id="quickReminderDate" type="datetime-local" placeholder=" " v-model="form.starts_at" /><label for="quickReminderDate"><span class="text-red-500">*</span> Data e hora</label></span></div><div class="field col-12 md:col-6"><span class="p-float-label"><Dropdown inputId="quickReminderRecurrence" v-model="form.recurrence_rule" :options="[{ label: 'Não repetir', value: 'none' }, { label: 'Todos os dias', value: 'daily' }, { label: 'Toda semana', value: 'weekly' }, { label: 'Todo mês', value: 'monthly' }]" optionLabel="label" optionValue="value" class="w-full reminder-select" /><label for="quickReminderRecurrence">Recorrência</label></span></div><div v-if="form.recurrence_rule !== 'none'" class="field col-12 md:col-6"><span class="p-float-label"><InputText id="quickReminderRecurrenceUntil" type="date" placeholder=" " v-model="form.recurrence_until" /><label for="quickReminderRecurrenceUntil">Repetir até</label></span></div><div class="field col-12"><span class="p-float-label"><Textarea id="quickReminderDescription" v-model="form.description" rows="3" /><label for="quickReminderDescription">Descrição</label></span></div><div class="field col-12 md:col-6"><span class="p-float-label"><Dropdown inputId="quickReminderService" v-model="form.service_id" :options="services" optionLabel="client" optionValue="id" filter showClear class="w-full reminder-select" /><label for="quickReminderService">Serviço vinculado</label></span></div><div class="field col-12 md:col-6"><span class="p-float-label"><Dropdown inputId="quickReminderSale" v-model="form.sale_id" :options="sales" optionLabel="customer_name" optionValue="id" filter showClear class="w-full reminder-select" /><label for="quickReminderSale">Venda vinculada</label></span></div></div><template #footer><Button label="Cancelar" text @click="emit('update:modelValue', false)" /><Button label="Salvar" icon="pi pi-check" :loading="loading" @click="save" /></template></Dialog></template>
<style scoped>.reminder-select { min-height: 2.75rem; }</style>
